In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.8 MB 27.3 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.8 MB 29.2 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 26.7 MB/s eta 0:00:00


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.2


In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import sys
import time

**PERFORMANCE COMPARISON**

**ARRAY DIMENSION**

In [12]:
arr = np.array(42)
print(arr)
print(type(arr))
print(arr.shape)
print("The dimension of the avove array is:", arr.ndim)

42
<class 'numpy.ndarray'>
()
The dimension of the avove array is: 0


In [ ]:
size = 100_00_000


**1-D (1 Dimensional Array)**

In [15]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print("The dimension of above array is :", arr.ndim)

[1 2 3 4 5]
(5,)
The dimension of above array is : 1


**2 Dimensional Array (2-D)**

In [17]:
variable = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(variable)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
arr = np.array([
    (1,3,5,7,9),
    (4,5,6,7,8)
    ])

print(arr)

[[1 3 5 7 9]
 [4 5 6 7 8]]


**3-D (3 Dimensional Array)**

In [24]:
arr = np.array(
    [
        [[1,2,3],
        [4,5,6]],
        [[7,8,9],
        [10,11,12]]
    ]
    )
print(arr)
print(arr.shape)
print("The dimension of the above numpy is: ", arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
The dimension of the above numpy is:  3
